version: '3.8'

services:
  sespec:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sespec
    volumes:
      - ./src:/home/yangfp/SESpec/src
      - ./data:/home/yangfp/SESpec/data
      - ./models:/home/yangfp/SESpec/models
    environment:
      - API_KEY=${API_KEY}
      - BASE_URL=${BASE_URL}
      - API_MODEL=${API_MODEL}
      - LLVM_CONFIG=/usr/bin/llvm-config-18
      - CC=clang-18
      - CXX=clang++-18
      - MODEL_PATH=/home/yangfp/SESpec/models
      - DATA_PATH=/home/yangfp/SESpec/data
    ports:
      - "7860:7860"
    command: >
      bash -c "llvm-config-18 --version && clang-18 --version && python src/main.py --config configs/air_config.yaml --function foo"
