#!/usr/bin/env python3
"""Append/refresh the strength_summary table at the end of large_experiment_table.tex.

Source (unified 4-model layout under RESULTS/paper_data/judge/):
  - judge/vs_autospec/{model}.csv  per-case verdicts (case_id, verdict, reason)
  - judge/vs_autospec/summary.csv  per-model aggregate
  - judge/vs_specgen/{model}.csv   per-case verdicts
  - judge/vs_specgen/summary.csv   per-model aggregate

Strategy: if the tex file already contains a strength_summary block, replace it;
otherwise append.
"""
from __future__ import annotations

import csv
import re
from pathlib import Path

PD = Path("/home/yangfp/SESpec/RESULTS/paper_data")
JUDGE = PD / "judge"
TEX = Path("/home/yangfp/SESpec/paper/FSEchapters/large_experiment_table.tex")

MODELS = ["gpt-4o", "gpt-5-mini", "gpt-5.4-mini", "gpt-5"]


def read_summary(baseline_label: str) -> dict[str, dict]:
    """Read judge/vs_<baseline>/summary.csv -> {model: {counts...}}."""
    p = JUDGE / f"vs_{baseline_label}" / "summary.csv"
    out: dict[str, dict] = {}
    if not p.exists():
        return out
    with p.open(encoding="utf-8") as f:
        for r in csv.DictReader(f):
            out[r["model"]] = {k: int(v) for k, v in r.items() if k != "model"}
    return out


def fmt_pct(n, total):
    if not total:
        return "---"
    return f"{round(n / total * 100, 1):.1f}\\%"


def emit_block(baseline_label: str, baseline_display: str) -> list[str]:
    rows = read_summary(baseline_label)
    lines = []
    n = sum(1 for m in MODELS if m in rows)
    first = True
    tot = {"both": 0, "bs": 0, "as": 0, "eq": 0, "ic": 0}
    for model in MODELS:
        r = rows.get(model)
        if not r:
            continue
        both = r["both_pass_total"]
        bs = r["B_stronger"]; as_ = r["A_stronger"]
        eq = r["equal"]; ic = r["incomparable"]
        tot["both"] += both; tot["bs"] += bs; tot["as"] += as_
        tot["eq"] += eq; tot["ic"] += ic
        method_cell = f"\\multirow{{{n}}}{{*}}{{{baseline_display}}}" if first else ""
        lines.append(
            f"{method_cell} & {model} & {both} & {bs} ({fmt_pct(bs, both)}) "
            f"& {as_} ({fmt_pct(as_, both)}) & {eq} & {ic} \\\\"
        )
        first = False
    lines.append(r"\cmidrule(lr){2-7}")
    lines.append(
        f" & \\emph{{Total}} & \\emph{{{tot['both']}}} & "
        f"\\emph{{{tot['bs']} ({fmt_pct(tot['bs'], tot['both'])})}} & "
        f"\\emph{{{tot['as']} ({fmt_pct(tot['as'], tot['both'])})}} & "
        f"\\emph{{{tot['eq']}}} & \\emph{{{tot['ic']}}} \\\\"
    )
    return lines


def build_table() -> str:
    lines = []
    lines.append("% Auto-generated by src/scripts/append_strength_summary_table.py")
    lines.append(r"\begin{table*}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Pairwise specification strength on the both-valid sets. An LLM-as-a-judge (\texttt{gpt-5.4-mini}) produces verdicts; rows for gpt-4o/gpt-5-mini/gpt-5.4-mini are post-human-review counts (paper-validated), the gpt-5 rows are LLM-only without human review.}")
    lines.append(r"\label{tab:strength_summary}")
    lines.append(r"\scriptsize")
    lines.append(r"\setlength{\tabcolsep}{6pt}")
    lines.append(r"\begin{adjustbox}{width=\textwidth}")
    lines.append(r"\begin{tabular}{llrrrrr}")
    lines.append(r"\toprule")
    lines.append(r"Baseline & Model & Both valid & \toolname\ stronger & Baseline stronger & Equal & Incomp. \\")
    lines.append(r"\midrule")
    lines.extend(emit_block("autospec", "AutoSpec (C/ACSL)"))
    lines.append(r"\midrule")
    lines.extend(emit_block("specgen", "SpecGen (Java/JML)"))
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{adjustbox}")
    lines.append(r"\end{table*}")
    return "\n".join(lines) + "\n"


def main():
    content = TEX.read_text(encoding="utf-8")
    new_block = build_table()
    # Remove any existing strength_summary block
    m = re.search(r"\n% Auto-generated by .*append_strength_summary.*", content)
    if m:
        # Trim everything from that marker to EOF
        content = content[:m.start()]
    # Also remove any older hand-written strength_summary table*
    pattern = re.compile(
        r"\n+\\begin\{table\*\}[^\n]*\n[\s\S]*?label\{tab:strength_summary\}[\s\S]*?\\end\{table\*\}",
        re.MULTILINE,
    )
    content = pattern.sub("", content)
    if not content.endswith("\n"):
        content += "\n"
    content += "\n" + new_block
    TEX.write_text(content, encoding="utf-8")
    print(f"Updated {TEX}")


if __name__ == "__main__":
    main()
