env_name: SpecAutoGen
api:
  base_url: https://api.openai.com/v1
  api_key_env: OPENAI_API_KEY
  temperature: 0.2
  top_p: 0.7
  max_tokens: 2048
models:
  - gpt-4o
  - gpt-5-nano
  - gpt-5-mini
  - gpt-5.4-nano
  - gpt-5.4-mini
tools:
  frama_c_cmd:
    - opam
    - exec
    - --switch=frama-c.27.1
    - --
    - frama-c
  openjml_cmd:
    - /home/yangfp/CAV-JAVA/.tools/openjml/current/openjml
paths:
  sespec_root: /home/yangfp/SESpec
  autospec_root: /home/yangfp/SESpec/represent/external/autospec
  specgen_root: /home/yangfp/SESpec/represent/external/specgen-artifact
  formalbench_root: /home/yangfp/SESpec/represent/external/formalbench
