main:
  root_dir: "FormalBench"
  function_name: "foo149"
  debug: false
  only_loop: false
  recursive_loop: false
  auto_annotation: true
  refine_count: 9
  pass_count: 1

llm:
  api_model: "gpt-5-nano"

preconditions:
  foo149: "emp"
