# main process config
main:
  root_dir: "linear"
  function_name: "foo1"
  debug: false
  recursive_loop: false
  auto_annotation: true
  refine_count: 9
  pass_count: 5

# LLM Config
llm:
  api_model: "gpt-4o"

# precondition config
preconditions:
  foo1: "emp"
